tasks:
  - init: python3 -m venv venv
  - command: python3 -m venv venv
  - init: source venv/bin/activate
  - command: source venv/bin/activate
  - init: pip3 install -r requirements.txt
  - command: pip3 install -r requirements.txt
      
      
vscode:
  extensions:
    - ms-python.python

image:
  file: .gitpod.dockerfile
