tasks:   
  - init: |
      python3 -m venv venv
      source venv/bin/activate
      pip3 install --upgrade pip
      pip3 install -r requirements.txt
vscode:
  extensions:
    - ms-python.python

image:
  file: .gitpod.dockerfile
